import csv
from pathlib import Path
from statistics import mean


def load_timeseries(csv_path):
    rows = []

    with open(csv_path, newline="") as handle:
        reader = csv.DictReader(handle)

        for row in reader:
            rows.append({
                "date": row["date"],
                "NDVI": float(row["NDVI"])
            })

    rows.sort(key=lambda r: r["date"])

    return rows


def synthesize_ndvi(csv_path):
    rows = load_timeseries(csv_path)

    if not rows:
        return """## Refusal

I cannot answer from the approved BON evidence.

Reason:
No NDVI observations were found.

What a human should consult instead:
The BON output files and pipeline logs.
"""

    values = [r["NDVI"] for r in rows]

    first = values[0]
    last = values[-1]
    minimum = min(values)
    maximum = max(values)
    average = mean(values)

    trend = "increased"

    if last < first:
        trend = "decreased"

    elif abs(last - first) < 0.02:
        trend = "remained relatively stable"

    return f"""## Answer

The BON NDVI time series contains {len(rows)} observations. The first NDVI value was {first:.3f} and the final NDVI value was {last:.3f}, indicating that NDVI {trend} over the observed period. The minimum observed NDVI value was {minimum:.3f}, the maximum was {maximum:.3f}, and the average NDVI value was {average:.3f}. (Source: BON NDVI timeseries.csv, local BON pipeline output)

## Evidence used

| Chunk ID | Title | Citation | Relevant passage |
|----------|--------|----------|------------------|
| bon-ndvi-timeseries | BON NDVI Time Series | Local BON in a Box NDVI pipeline output | {len(rows)} NDVI observations loaded from timeseries.csv |

## Uncertainty and gaps

The time series provides NDVI measurements but does not explain ecological causes, land-cover changes, or biodiversity impacts. NDVI is a vegetation indicator and should not be interpreted as a direct biodiversity measure without additional evidence.

## Assumptions

The NDVI column in timeseries.csv is assumed to represent the requested summary statistic generated by the BON NDVI pipeline.

## Human review needed

An ecologist should inspect the generated NDVI plot and verify whether the selected area, date range, and summary statistic are appropriate for the intended analysis.
"""


if __name__ == "__main__":

    csv_file = "../inputRouting/runs/20260610-175715/timeseries.csv"

    answer = synthesize_ndvi(csv_file)

    print(answer)
